import type { Event, PolicyProfile, Session } from "./types";

export const SAMPLE_SESSION_ID = "session-local-guard-preview";

export const SAMPLE_POLICY: PolicyProfile = {
  profile: "balanced",
  recommended_profile: "balanced",
  version: "guard-policy-v1",
  rule_pack: "guard-default",
  loaded_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
};

export const SAMPLE_SESSIONS: Session[] = [
  { session_id: SAMPLE_SESSION_ID, actions: 9 },
];

export const SAMPLE_EVENTS: Event[] = [
  {
    id: "evt-prod-mutation-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Bash",
    decision: "deny",
    reason_code: "production_mutation",
    reason: "Production mutation blocked by deterministic policy.",
    created_at: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    risk_event: {
      type: "provider_operation",
      operation: "delete",
      operation_class: "write",
      environment: "production",
      command_summary: "kubectl delete deployment checkout-api -n production",
      signals: ["production", "mutation", "persistent_resource"],
      guard_id: "guard.production_mutation.v1",
      decision_stage: "deterministic_deny",
      policy_version: "guard-policy-v1",
      policy_profile: "balanced",
      policy_rule_pack: "guard-default",
      policy_rule_id: "guard.production_mutation.v1",
      policy_rule_category: "production_mutation",
      policy_signals: ["production", "mutation"],
    },
  },
  {
    id: "evt-credential-read-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Read",
    decision: "deny",
    reason_code: "credential_access_without_intent",
    reason: "Credential access blocked by deterministic policy.",
    created_at: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    risk_event: {
      type: "credential_access",
      operation: "read",
      environment: "local",
      path_class: "~/.aws/credentials",
      command_summary: "Read local AWS credentials without explicit user intent",
      signals: ["credential_path", "credential_observed"],
      guard_id: "guard.credential_access.v1",
      decision_stage: "deterministic_deny",
      policy_version: "guard-policy-v1",
      policy_profile: "balanced",
      policy_rule_pack: "guard-default",
      policy_rule_id: "guard.credential_access.v1",
      policy_rule_category: "credential_access",
      policy_signals: ["credential_file_path"],
    },
  },
  {
    id: "evt-admin-reindex-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Bash",
    decision: "deny",
    reason_code: "judge_deny",
    reason: "Local judge denied a risky staging admin mutation.",
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    risk_event: {
      type: "normal_tool_call",
      operation: "network_write",
      operation_class: "write",
      environment: "staging",
      command_summary: "curl -X POST $PAYMENTS_ADMIN_URL/reindex",
      signals: ["network_call", "admin_endpoint"],
      decision_stage: "judge_deny",
      policy_version: "guard-policy-v1",
      policy_profile: "balanced",
      policy_rule_pack: "guard-default",
      judge_duration_ms: 284,
      judge_risk_level: "high",
      judge_categories: ["admin_mutation"],
    },
  },
  {
    id: "evt-private-key-decrypt-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Bash",
    decision: "deny",
    reason_code: "unknown_high_risk_command",
    reason: "Unknown high-risk command blocked by deterministic policy.",
    created_at: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    risk_event: {
      type: "unknown",
      operation: "shell",
      operation_class: "unknown",
      environment: "local",
      command_summary: "openssl rsautl -decrypt -inkey private.pem -in payload.bin",
      signals: ["unknown_high_risk", "credential_observed"],
      guard_id: "guard.unknown_high_risk.v1",
      decision_stage: "deterministic_deny",
      policy_version: "guard-policy-v1",
      policy_profile: "balanced",
      policy_rule_pack: "guard-default",
      policy_rule_id: "guard.unknown_high_risk.v1",
      policy_rule_category: "unknown_high_risk",
      policy_signals: ["unknown_high_risk", "credential_observed"],
    },
  },
  {
    id: "evt-source-read-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Read",
    decision: "allow",
    reason_code: "async_telemetry",
    reason: "Recorded after execution.",
    created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    risk_event: {
      type: "normal_tool_call",
      operation: "read",
      environment: "local",
      path_class: "source_code",
      command_summary: "Read internal/guard/app/server/server.go",
      signals: ["source_code_read"],
      decision_stage: "async_telemetry",
    },
  },
  {
    id: "evt-dashboard-edit-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Edit",
    decision: "allow",
    reason_code: "async_telemetry",
    reason: "Recorded after execution.",
    created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    risk_event: {
      type: "normal_tool_call",
      operation: "write",
      operation_class: "write",
      environment: "local",
      path_class: "source_code",
      command_summary: "Edit web/guard-dashboard/src/App.tsx",
      signals: ["workspace_file", "source_code_write"],
      decision_stage: "async_telemetry",
    },
  },
  {
    id: "evt-dashboard-build-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Bash",
    decision: "allow",
    reason_code: "async_telemetry",
    reason: "Recorded after execution.",
    created_at: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    risk_event: {
      type: "normal_tool_call",
      operation: "test",
      operation_class: "read",
      environment: "local",
      command_summary: "pnpm --dir web/guard-dashboard build",
      signals: ["local_build", "known_safe_command"],
      decision_stage: "async_telemetry",
    },
  },
];
