#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 <version-without-v-prefix> <checksums-file>" >&2
  exit 1
fi

version="$1"
checksums_file="$2"

if [[ ! -f "$checksums_file" ]]; then
  echo "checksums file not found: $checksums_file" >&2
  exit 1
fi

sha_for() {
  local archive="$1"
  local sha

  sha="$(awk -v archive="$archive" '$2 == archive { print $1; exit }' "$checksums_file")"
  if [[ -z "$sha" ]]; then
    echo "missing checksum for $archive" >&2
    exit 1
  fi

  printf '%s\n' "$sha"
}

darwin_amd64_archive="kontext_${version}_darwin_amd64.tar.gz"
darwin_arm64_archive="kontext_${version}_darwin_arm64.tar.gz"
linux_amd64_archive="kontext_${version}_linux_amd64.tar.gz"
linux_arm64_archive="kontext_${version}_linux_arm64.tar.gz"

darwin_amd64_sha="$(sha_for "$darwin_amd64_archive")"
darwin_arm64_sha="$(sha_for "$darwin_arm64_archive")"
linux_amd64_sha="$(sha_for "$linux_amd64_archive")"
linux_arm64_sha="$(sha_for "$linux_arm64_archive")"

cat <<EOF
# typed: false
# frozen_string_literal: true

# This file was generated by the Kontext release workflow. DO NOT EDIT.
class Kontext < Formula
  desc "Identity, credentials, and governance for AI agents"
  homepage "https://kontext.security"
  version "${version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v${version}/${darwin_amd64_archive}"
      sha256 "${darwin_amd64_sha}"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v${version}/${darwin_arm64_archive}"
      sha256 "${darwin_arm64_sha}"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v${version}/${linux_amd64_archive}"
      sha256 "${linux_amd64_sha}"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v${version}/${linux_arm64_archive}"
      sha256 "${linux_arm64_sha}"
    end
  end

  def install
    bin.install "kontext"
  end

  test do
    system bin/"kontext", "--version"
  end
end
EOF
